debug:
  mode: true
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
mybatis:
  type-aliases-package: com.kennyw.springbootdemo.domain