package com.kennyw.springbootmybatis.model;

import java.io.Serializable;

public class Girl implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girl.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girl.age
     *
     * @mbggenerated
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girl.cup_size
     *
     * @mbggenerated
     */
    private String cupSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table girl
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girl.id
     *
     * @return the value of girl.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girl.id
     *
     * @param id the value for girl.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girl.age
     *
     * @return the value of girl.age
     *
     * @mbggenerated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girl.age
     *
     * @param age the value for girl.age
     *
     * @mbggenerated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girl.cup_size
     *
     * @return the value of girl.cup_size
     *
     * @mbggenerated
     */
    public String getCupSize() {
        return cupSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girl.cup_size
     *
     * @param cupSize the value for girl.cup_size
     *
     * @mbggenerated
     */
    public void setCupSize(String cupSize) {
        this.cupSize = cupSize == null ? null : cupSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table girl
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", age=").append(age);
        sb.append(", cupSize=").append(cupSize);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}