package com.kennyw.springbootmybatis.dao;

import com.kennyw.springbootmybatis.model.Girl;
import com.kennyw.springbootmybatis.model.GirlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GirlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table girl
     *
     * @mbggenerated
     */
    int countByExample(GirlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table girl
     *
     * @mbggenerated
     */
    int deleteByExample(GirlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table girl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table girl
     *
     * @mbggenerated
     */
    int insert(Girl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table girl
     *
     * @mbggenerated
     */
    int insertSelective(Girl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table girl
     *
     * @mbggenerated
     */
    List<Girl> selectByExample(GirlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table girl
     *
     * @mbggenerated
     */
    Girl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table girl
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Girl record, @Param("example") GirlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table girl
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Girl record, @Param("example") GirlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table girl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Girl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table girl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Girl record);
}